version: '3.9'
services:
  jupyter:
    build: .
    container_name: Jupyter
    security_opt:
      - no-new-privileges:true
    volumes:
      - jupyter_data:/home/lewis/work:rw
    ports:
      - 10235:8888
    restart: on-failure:5

volumes:
  jupyter_data:  # Define the named volume
